{{- if .Values.preJob.preConfig.enable }}
  apiVersion: batch/v1
   kind: Job
   metadata:
   name: {{ .Release.Name }}-init-config
  annotations:
      "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "2"
    labels:
  {{ include "service.labels.standard" . | indent 4 }}
  spec:
      backoffLimit: 1
        activeDeadlineSeconds: {{ .Values.preJob.timeout | default 300 }}
        template:
            metadata:
              name: {{ .Release.Name }}-init-config
              spec:
                  containers:
                    - name: {{ .Release.Name }}-init-config
                    image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    env:
                    - name: DB_HOST
                    value: {{ .Values.preJob.preConfig.db.host }}
                    - name: DB_PORT
                      value: {{ .Values.preJob.preConfig.db.port | quote }}
                    - name: DB_USER
                      value: {{ .Values.preJob.preConfig.db.username }}
                    - name: DB_PASS
                      value: {{ .Values.preJob.preConfig.db.password }}
                    - name: DB_NAME
                      value: {{ .Values.preJob.preConfig.db.dbname }}
                    - name: UP_ATTRS
                      value: {{ .Values.preJob.preConfig.db.upattrs }}
  {{- if .Values.preJob.preConfig.db.type }}
      - name: DB_TYPE
        value: {{ .Values.preJob.preConfig.db.type }}
      {{- end }}
          command:
          - /bin/sh
          - -c
          - '
          cd /usr/share/nginx/html;
          python ./menu/__init__.py -o sql -d {{ .Values.preJob.preConfig.db.enabledelete }};
          python ./dashboard/__init__.py -o sql -d {{ .Values.preJob.preConfig.db.enabledelete }};
          '
          restartPolicy: Never
        {{- end }}
